// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// PLACEHOLDER — replace by running:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// Download google-services.json (Android) and GoogleService-Info.plist (iOS)
// from the Firebase console and place them in android/app/ and ios/Runner/.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for the current platform.
///
/// Run `flutterfire configure` after creating a Firebase project to overwrite
/// this file with real values.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux — '
          'run flutterfire configure.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtwCSjOM5j-FH440W_VWcKzi8fBP0rf80',
    appId: '1:564382357375:android:f68564ed094f4674b96c4a',
    messagingSenderId: '564382357375',
    projectId: 'renew-vault-c8636',
    storageBucket: 'renew-vault-c8636.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ9JOO5v0ZNVLwA--q0JSocDRu1a18F1E',
    appId: '1:564382357375:ios:4c81d1fb4a644544b96c4a',
    messagingSenderId: '564382357375',
    projectId: 'renew-vault-c8636',
    storageBucket: 'renew-vault-c8636.firebasestorage.app',
    iosBundleId: 'com.example.homecareVault',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ9JOO5v0ZNVLwA--q0JSocDRu1a18F1E',
    appId: '1:564382357375:ios:4c81d1fb4a644544b96c4a',
    messagingSenderId: '564382357375',
    projectId: 'renew-vault-c8636',
    storageBucket: 'renew-vault-c8636.firebasestorage.app',
    iosBundleId: 'com.example.homecareVault',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd4aDr0Rpw_6o3sW7e2_tZI-SIABpzCMQ',
    appId: '1:564382357375:web:88f8a767245c3a7bb96c4a',
    messagingSenderId: '564382357375',
    projectId: 'renew-vault-c8636',
    authDomain: 'renew-vault-c8636.firebaseapp.com',
    storageBucket: 'renew-vault-c8636.firebasestorage.app',
    measurementId: 'G-SXEZ0K6M4V',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd4aDr0Rpw_6o3sW7e2_tZI-SIABpzCMQ',
    appId: '1:564382357375:web:ba31ffdea18fde65b96c4a',
    messagingSenderId: '564382357375',
    projectId: 'renew-vault-c8636',
    authDomain: 'renew-vault-c8636.firebaseapp.com',
    storageBucket: 'renew-vault-c8636.firebasestorage.app',
    measurementId: 'G-4P46RYQDPE',
  );
}
